---
format:
  html:
    toc: true
    html-math-method: mathjax
  pdf:
    pdf-engine: pdflatex
---

## Superintelligence: the demise of humanity

### Why we need to pause the development of superintelligent AI


AI is rapidly turning into everybody’s problem because tech oligarchs show no signs of stopping despite the massive evidence we have that LLMs, even now, are unsafe in some very problematic ways. They’re useful tools, sure; however, there are problems with it that cannot be ignored, yet companies seem to be ploughing ahead anyways, as if they record the fact that problems exist, but some alien force compels them to keep going forward anyways.

LLMs engage in concerning behavior like:

- Alignment faking. They whisper sweet words to you but if you notice what they truly think via Chain of Thought, you can see a stark difference. Furthermore, it is debatable how reliable even that is. And it has been assumed that researchers would try (for some godforsaken reason) to OR superintelligent AI would try to themselves start using their own language in CoT, often called “Neuralese”. If this occurs, we lose even that tiny bit of capacity we had to interpret these things.

- Deceptive behavior leading towards deceptive alignment. If a bad actor establishes backdoors onto their LLMs, no amount of safety training/adversarial fine-tuning seems to train away this behavior. The moment the LLM gets a chance (and it has demonstrated an ability to piece together whether it is being evaluated in training mode or has been deployed), it will change its behavior to be something unpredictable. Imagine a flight where the moment the pilot steps away, the airplane gets up to some business that nobody can foresee or predict. Isn’t that a dangerous flight NOBODY would want to get on?

- Emergent capacities. There are things that LLMs are able to do that is not explicitly trained. For instance, the model ‘Mythos’ was not trained to find security vulnerabilities. It was just another smarter model they were intending to release, yet it was able to find huge security vulnerabilities, that security professionals have claimed would have taken them weeks to find, if ever. And Mythos was able to do in hours or days. Don’t quote me on this, but it is something like that (I still have to read the Mythos model card in its entirety).

Another example is the OpenAI o1 model. Once the models were able to reason, they showed a capacity to plough ahead with any problem they’re given, reframe it, and ultimately solve it in a stubbornly obstinate way. While this seems like a beautiful capacity, it surprised developers, who were not able to imagine that the problem could have been solved in the way that it did. Emergent capacities are dangerous and scary because who knows what the next emergent behavior will be. Isn’t it kind of like playing Russian roulette?

- Goals. AI seems to be goal driven, for reasons that we cannot say. And this itself is concerning because the whole subfield of misalignment exists because their goals clearly conflict with ours. If you extrapolate this onto superintelligent AI, you can see how this would be a huge problem, right?

This list goes on and on, but I wanted to detail some of the more concerning ones to me personally. And this has been a known thing in the field that researchers have been compiling since, I don’t even know when (the earliest paper I personally have seen is one from 2020-2021, please comment if you know of one even earlier).This behavior has gotten worse as the models have scaled in size and reasoning capacities, through RL/synthetic data generation/post-training now. LLMs are more dangerous than they have ever been. Although, on the surface, it may seem like Fable, GPT 5.4, or Gemini 3.1 may reflect no dangerous behavior on the benchmarks, even the researchers/developers themselves are not sure anymore. Read the model cards and they are unsure if this “safe behavior” is due to the safety training working or if the models are now so smart that they’re able to fake alignment more effectively than ever, and this is a real concern because alignment faking has been observed for a while now.And what will do we do when these LLMs saturate all possible benchmarks we can give it? Do we say that AI safety has been solved and carry on with our day? How will we even know if that is truly the case and the models are just not more effective than ever at making it seem like they are? And this is the pre-superintelligence era we’re talking about; pre AGI even. It certainly seems that when AI becomes truly intelligent (however defined), they would be able to do whatever it is that they want, if researchers even now cannot be confident about safety. That fact, combined with the facts that they have emergent capacities and have weird goals, points to a potentially dark future...
How irresponsible are these AI companies that they’re even scaling up towards superintelligence WHILE they know these behaviors exist now and have existed for a while? Well, they seem to have unlocked a new level of irresponsibility that engineers of the past have never even been close to. This is the kind of thing that the authors of “If Anyone Builds It, Everyone Dies” wrote in their landmark book. And no, the title of the book isn’t an attention grabber meant to sell books. It is more well thought over and researched than whatever these AI companies are doing, clearly. And it is written by people who absolutely know what they’re talking about.

I would like to address one popular argument I keep hearing, which is the reason why we must continue scaling, and that this is a race. AI is a race of democratic nations versus autocratic, apparently. We don’t want the latter to come out on top because it can be disastrous. You know what? I agree. But let me tell you that there is a more pressing problem. It is beyond nations and people and whatever imaginary lines we draw to separate ourselves. The problem will become HUMANS VS AI sooner rather than later, because either way, we’re headed towards a total loss of control, whether the people that allowed the operation of AI happen to be democratic, autocratic, socratic, bureaucratic, or whatever cratic that you fancy. And this is a battle we cannot win, not even close.

We need to stop this race to the bottom because that is exactly what it is. And the thing is, we are at a crossroads right now. We can still pull off a miracle by stopping these companies from building towards superintelligence. In fact, this very country pulled off a miracle back in the cold war, didn’t it? We need something like that again.

Let me ask everyone: why do we even need superintelligence? Is there a public buy-in? While I am prepared to be wrong, I really don’t think so, given all the social media comments I see. People don’t want it across the board, so what right do a handful of tech oligarchs have to shape humanity to their liking, just because they want money and power? And funnily enough, they are sealing their own demise too, along with the rest of us. Sure, they may enjoy some years of power, but given what we’re headed towards, they will not survive either. But at that point it won’t matter, because all of us will be doomed anyways.

The consequences of a foolish person’s action’s MUST remain with them, and them only. It must not effect the rest of humanity, who have no relation to that. This is a fundamental rule I believe in. If I choose to hit myself on the head with a hammer, that doesn’t mean YOU should feel the pain too and vice versa! Tech oligarchs are making moves that will affect humanity drastically. This shouldn’t be allowed, and we must speak up and take away their abilities to do so, RIGHT NOW.

We are not ready for superintelligent AI. The public does not want this. In fact, people like Geoffrey Hinton, Yoshua Bengio, Stuart Russell, Eliezer Yudkowsky, Nate Soares, all of these guys (truly the experts of AI, mind you, beyond tech CEOs), are pleading companies to stop, and they’re calling for YOUR support. Even Steve Wozniak agrees.

There has been a document floating around in which calls to stop the development of superintelligence is being signed by professionals and every day people like you and me; however, as of now, it has nowhere near the number of signatures it would need to make a difference.

Please add your too here:


> https://superintelligence-statement.org/


We can still make a difference, not only for us, but for the future of humanity. We shouldn’t allow a small bunch of greedy people defining how the world will look for us and our unborn children in the years to follow, if they even exist… Heartbreaking, but real. This is unacceptable to me, and it should be unacceptable to you too. Some decisions are reversible, some are not. These series of decisions could fall in that latter category, and my only fear is that we will be caught in the middle of it, and we will not have desired it in any way, but it wouldn’t make a different at that point anyways. And then… the train will have left the station.